---
- hosts: all
  become: true
  
  ##################################################################
  #########################      VARS      #########################
  ##################################################################

  vars:
    operating_system: "Ubuntu-24.04-amd64"

    # Obtained from https://veracrypt.io/en/Digital%20Signatures.html
    veracrypt_public_key: "5069A233D55A0EEB174A5FC3821ACD02680D16DE"
    ##################################################################
    ######################### Veracrypt VARS #########################
    ##################################################################
    # Obtained from https://veracrypt.io/en/Downloads.html
    veracrypt_version: "1.26.29"
    veracrypt_deb: "veracrypt-{{ veracrypt_version }}-{{ operating_system }}.deb"
    veracrypt_sig: "veracrypt-{{ veracrypt_version }}-{{ operating_system }}.deb.sig"
    veracrypt_url: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/{{ veracrypt_deb }}"
    veracrypt_sig_url: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/{{ veracrypt_sig }}"
    veracrypt_sha256: "5688384F062BE97405829EBC193C3BB4B286F1511E5EFC96D7CEAB9679D895BB"
    veracrypt_pgp_public_key_url: "https://amcrypto.jp/VeraCrypt/VeraCrypt_PGP_public_key.asc"


  ##################################################################
  #########################      TASKS      ########################
  ##################################################################
  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
      
    - name: Install gnupg for deb8222 and veracrypt install verification
      ansible.builtin.apt:
        name: 
          - gnupg # Required for pgp keys
          - python3-debian # Required for ansible.builtin.deb822_repository to work correctly
        state: present
        update_cache: true
        autoclean: true

    ###############  Veracrypt  ###############
    - name: Veracrypt Install
      block:
      - name: Download VeraCrypt {{ veracrypt_version }} package
        get_url:
          url: "{{ veracrypt_url }}"
          dest: "/tmp/{{ veracrypt_deb }}"

      - name: Download VeraCrypt {{ veracrypt_version }} signature
        get_url:
          url: "{{ veracrypt_sig_url }}"
          dest: "/tmp/{{ veracrypt_sig }}"

      - name: Download VeraCrypt public PGP key
        get_url:
          url: "{{ veracrypt_pgp_public_key_url }}"
          dest: /tmp/VeraCrypt_PGP_public_key.asc

      - name: Read key fingerprint without importing
        command:
          cmd: >
            gpg --import --import-options show-only /tmp/VeraCrypt_PGP_public_key.asc
        register: gpg_key_info
        changed_when: false

      - name: Verify VeraCrypt public key fingerprint
        assert:
          that:
            - veracrypt_public_key == veracrypt_public_key
          fail_msg: >-
            Fingerprint mismatch.
            Expected {{ veracrypt_public_key }}
            but found {{ veracrypt_public_key }}
          success_msg: VeraCrypt public key fingerprint verified.

      - name: Import VeraCrypt public key
        command:
          cmd: gpg --import /tmp/VeraCrypt_PGP_public_key.asc
        when: veracrypt_public_key == veracrypt_public_key

      - name: Verify VeraCrypt PGP signature
        command:
          cmd: >
            gpg --verify
            /tmp/{{ veracrypt_sig }}
            /tmp/{{ veracrypt_deb }}
        register: gpg_verify
        changed_when: false
        
      - name: Verify VeraCrypt SHA256 checksum
        stat:
          path: "/tmp/{{ veracrypt_deb }}"
          checksum_algorithm: sha256
        register: veracrypt_stat
      
      - name: Validate Veracrypt download computed SHA256 value and veracypt expected SHA256 value
        fail:
          msg: "SHA256 mismatch {{ veracrypt_stat }}"
        # | lower required to make sure the hash checksums are equivalent and there isn't any funky case stuff happening here
        when: veracrypt_stat.stat.checksum | lower != veracrypt_sha256 | lower 

      - name: Installing VeraCrypt
        apt:
          deb: "/tmp/{{ veracrypt_deb }}"


    ###############  Veracrypt  ###############
    - name: Add yubikey PPA
      block:
      - name: Fetch Yubico PPA key
        ansible.builtin.get_url:
          url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFA4EC8F2EE58CE0B"
          dest: /tmp/yubico.asc
      
      - name: Convert PPA key to keyring
        ansible.builtin.command:
          cmd: >
            gpg --dearmor
            --output /usr/share/keyrings/yubico-archive-keyring.gpg
            /tmp/yubico.asc
        args:
          creates: /usr/share/keyrings/yubico-archive-keyring.gpg
    
      - name: Add Yubico repository
        ansible.builtin.deb822_repository:
          name: yubico
          types: [deb]
          uris:
            - https://ppa.launchpadcontent.net/yubico/stable/ubuntu
          suites:
            - noble
          components:
            - main
          signed_by: /usr/share/keyrings/yubico-archive-keyring.gpg

      - name: Update and install yubikey-manager
        apt:
          name: yubikey-manager
          state: present
          update_cache: true
          autoclean: true